"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os

from decouple import config
from pathlib import Path
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost', cast=lambda v: [s.strip() for s in v.split(',')])


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'whichgame',
    'tailwind',
    'theme',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en'

TIME_ZONE = 'Europe/Paris'

USE_I18N = True

USE_TZ = True

LANGUAGES = [
    ('en', _('English')),
    ('fr', _('Français')),
]

# Dossier et fichiers de traduction
LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [ 
    BASE_DIR / 'static', 
    ]

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / "mediafiles"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Tailwind Settings
TAILWIND_APP_NAME = 'theme'
INTERNAL_IPS = ["127.0.0.1"]

# Django Sites Framework
SITE_ID = 1

# --- CONFIGURATION JAZZMIN ---
JAZZMIN_SETTINGS = {
    # 1. Titres et Marque
    "site_title": "WhichGame Admin",
    "site_header": "WhichGame",
    "site_brand": "WhichGame HQ",
    "welcome_sign": "Bienvenue, Commandant",
    "copyright": "Clement Lazzarini",
    
    # 2. Logo et Apparence
    "site_logo": "images/favicon.png", 
    "site_logo_classes": "img-circle",
    
    # 3. Avatar utilisateur (optionnel, sinon laisse None)
    "user_avatar": None,

    # 4. Menu Latéral et Navigation
    "search_model": ["whichgame.Game"], 

    # Liens rapides en haut (Top Menu)
    "topmenu_links": [
        {"name": "Voir le site", "url": "home", "permissions": ["auth.view_user"]},
        {"name": "Google Analytics", "url": "https://search.google.com/", "new_window": True},
        {"model": "whichgame.Game"},
    ],

    "custom_links": {
        "whichgame": [
            # 1. Import Global (Bouton Direct)
            {
                "name": "🔄 Import Jeux (Global)", 
                "url": "/admin/cmd/import_games/",
                "icon": "fas fa-globe",
                "permissions": ["auth.view_user"]
            },
            # 2. Import Franchise (Ouvre le formulaire)
            {
                "name": "📦 Import Franchise...", 
                "url": "import_franchise_wizard",
                "icon": "fas fa-search-plus",
                "permissions": ["auth.view_user"]
            },
            # 3. Recalcul IA (Bouton Direct)
            {
                "name": "🧠 Recalculer IA", 
                "url": "/admin/cmd/calculate_recommendations/",
                "icon": "fas fa-brain",
                "permissions": ["auth.view_user"]
            },
        ]
    },

    # Liens dans le menu latéral
    "order_with_respect_to": ["whichgame", "auth"],

    # 5. Icônes (FontAwesome 5)
    # Trouve les codes ici : https://fontawesome.com/v5/search
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user-astronaut",
        "auth.Group": "fas fa-users",
        
        "whichgame.Game": "fas fa-gamepad",
        "whichgame.GameCollection": "fas fa-layer-group",
    },
    
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    
    # Affiche ou non le constructeur d'interface
    "show_ui_builder": False,

    # 6. CSS Personnalisé
    "custom_css": "css/admin_custom.css",
}

# --- UI TWEAKS (LE LOOK GAMING SOMBRE) ---
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    
    # Couleurs de la barre du haut
    "brand_colour": "navbar-indigo",
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    
    # Le Thème Sombre
    "sidebar": "sidebar-dark-indigo",
    "sidebar_nav_small_text": False,
    "theme": "cosmo",
    
    # Personnalisation des boutons
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}