# Generated by Django 5.2.8 on 2025-11-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('cover_url', models.URLField(blank=True)),
                ('platforms', models.JSONField(default=list)),
                ('genres', models.JSONField(default=list)),
                ('rating', models.FloatField(null=True)),
                ('price_current', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('playtime_main', models.IntegerField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
