# Generated by Django 5.2.8 on 2026-01-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igdb_id', models.IntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('cover_url', models.URLField(blank=True, max_length=500)),
                ('summary', models.TextField(blank=True, null=True)),
                ('platforms', models.JSONField(default=list)),
                ('genres', models.JSONField(default=list)),
                ('themes', models.JSONField(blank=True, default=list)),
                ('rating', models.IntegerField(blank=True, db_index=True, null=True)),
                ('total_rating_count', models.IntegerField(blank=True, db_index=True, null=True)),
                ('price_current', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=6, null=True)),
                ('playtime_main', models.IntegerField(blank=True, db_index=True, null=True)),
                ('release_year', models.IntegerField(blank=True, db_index=True, null=True)),
                ('first_release_date', models.DateField(blank=True, null=True)),
                ('game_type', models.IntegerField(default=0)),
                ('remake_slug', models.CharField(blank=True, max_length=255, null=True)),
                ('video_id', models.CharField(blank=True, max_length=50, null=True)),
                ('screenshots', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('similar_games', models.ManyToManyField(blank=True, related_name='recommended_by', to='whichgame.game')),
            ],
        ),
        migrations.CreateModel(
            name='GameCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titre de la collection')),
                ('subtitle', models.CharField(max_length=255, verbose_name='Sous-titre (ex: Note min 90)')),
                ('url_filter', models.CharField(blank=True, help_text='Ex: ?rating=90 ou ?price=10 (laisser vide pour cacher le bouton)', max_length=255)),
                ('theme_color', models.CharField(choices=[('yellow', 'Jaune (Top Rated)'), ('green', 'Vert (Budget)'), ('purple', 'Violet (New)'), ('blue', 'Bleu (Standard)'), ('red', 'Rouge (Hot)')], default='blue', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('games', models.ManyToManyField(blank=True, related_name='collections', to='whichgame.game')),
            ],
            options={
                'verbose_name': 'Collection Home',
                'verbose_name_plural': 'Collections Home',
                'ordering': ['display_order'],
            },
        ),
    ]
