# Generated by Django 5.2.8 on 2025-11-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whichgame', '0002_game_igdb_id_alter_game_cover_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
