# Generated by Django 5.2.8 on 2025-11-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whichgame', '0003_alter_game_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='igdb_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='playtime_main',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='price_current',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='rating',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
