# Generated by Django 5.2.8 on 2025-11-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whichgame', '0004_alter_game_igdb_id_alter_game_playtime_main_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='release_year',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
