# Generated by Django 5.2.8 on 2025-12-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whichgame', '0005_game_release_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_type',
            field=models.IntegerField(default=0),
        ),
    ]
