# Generated by Django 5.2.8 on 2025-12-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whichgame', '0006_game_game_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='remake_slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
