# Generated by Django 5.2.8 on 2025-12-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whichgame', '0007_game_remake_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='screenshots',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='game',
            name='video_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
