# Generated by Django 5.2.8 on 2026-01-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whichgame', '0008_game_screenshots_game_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='first_release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='similar_games',
            field=models.ManyToManyField(blank=True, related_name='recommended_by', to='whichgame.game'),
        ),
        migrations.AddField(
            model_name='game',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='themes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='game',
            name='total_rating_count',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
