# Generated by Django 5.2.8 on 2026-01-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whichgame', '0009_game_first_release_date_game_similar_games_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titre de la collection')),
                ('subtitle', models.CharField(max_length=255, verbose_name='Sous-titre (ex: Note min 90)')),
                ('url_filter', models.CharField(blank=True, help_text='Ex: ?rating=90 ou ?price=10 (laisser vide pour cacher le bouton)', max_length=255)),
                ('theme_color', models.CharField(choices=[('yellow', 'Jaune (Top Rated)'), ('green', 'Vert (Budget)'), ('purple', 'Violet (New)'), ('blue', 'Bleu (Standard)'), ('red', 'Rouge (Hot)')], default='blue', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('games', models.ManyToManyField(blank=True, related_name='collections', to='whichgame.game')),
            ],
            options={
                'verbose_name': 'Collection Home',
                'verbose_name_plural': 'Collections Home',
                'ordering': ['display_order'],
            },
        ),
    ]
